Create italian Translation
TTT-2/ttt2-wep_doorlocker pull request #3
Opened 2020-10-09 16:24 UTC by ThePlatinumGhost

2020-10-20 20:05 UTC, Alf21 requested changes

2020-10-20 20:05 UTC, Alf21 commented on lua/terrortown/lang/italian/doorlocker.lua
> +L = LANG.GetLanguageTableReference("italiano")
```suggestion
local L = LANG.GetLanguageTableReference("italiano")
```

2020-10-21 12:09 UTC, ThePlatinumGhost commented
fixed

2020-10-22 15:37 UTC, Alf21 approved these changes

2020-10-30 21:06 UTC, merged